### ISSUE TITLE
installation problem - backend

### ISSUE THREAD

**Issue by mareczek82** [LibrePhotos/librephotos-docker#100]
Hi,

i folowed strictly with instructions 

changed only in .env file 
```
# Location of your photos.
/media/storage/librephotos/=./librephotos/pictures

# Internal data of LibrePhotos
/opt/librephotosdocker/=./librephotos/data


+dbPass 
```

but i have following message after try to run docker (its from second run, in first was sam plus info about downloading)

> marek@HPNAS ~/librephotos-docker (main)> docker-compose up -d
WARNING: The scanDirectory variable is not set. Defaulting to a blank string.
WARNING: The data variable is not set. Defaulting to a blank string.
db is up-to-date
redis is up-to-date
frontend is up-to-date
Creating backend ... error
ERROR: for backend  Cannot create container for service backend: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for backend  Cannot create container for service backend: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.

any ideas what went wrong?

**Comment by derneuere** [comment]
You replaced the wrong part in your .env. data and scanDirectory are the names of the variables, which have to have a value.
So /media/storage/librephotos/=./librephotos/pictures should be scanDirectory=/media/storage/librephotos/ and /opt/librephotosdocker/=./librephotos/data should be data=/opt/librephotosdocker/
