### ISSUE TITLE
"failed to register layer: unlinkat" error message after docker installation

### ISSUE THREAD

**Issue by GrumpyHose** [LibrePhotos/librephotos-docker#102]
Proxmox server 8.0.3.
Fresh Debian 12 running in an LXC container.
Fresh Docker installation verified working with hello-world image.
At the final step of the LibrePhotos install I get the following error: "failed to register layer: unlinkat /usr/local/lib/python3.11/dist-packages/Jinja2-3.1.2.dist-info: invalid argument"

Nothing accessible via http(s)://192.168.1.104:3000
Not sure where to go from here. 
![image](https://github.com/LibrePhotos/librephotos-docker/assets/139010478/66d005d0-c872-4242-9829-084e82aa8fd8)

**Comment by derneuere** [comment]
This seems to be a proxmox and docker issue: https://forum.proxmox.com/threads/docker-failed-to-register-layer-applylayer-exit-status-1-stdout-stderr-unlinkat-var-log-apt-invalid-argument.119954/

**Comment by GrumpyHose** [comment]
> This seems to be a proxmox and docker issue: https://forum.proxmox.com/threads/docker-failed-to-register-layer-applylayer-exit-status-1-stdout-stderr-unlinkat-var-log-apt-invalid-argument.119954/

Thank you so much!!! I was going crazy trying to figure this one out.
