### ISSUE TITLE
Kubernetes backend proxy container does not start

### ISSUE THREAD

**Issue by qdii** [LibrePhotos/librephotos-docker#110]
It fails with:

```
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```

The problem comes from setting `runAsUser: 66534` in the security context: only root can bind to low port numbers.

**Comment by quartztester** [comment]
@qdii Can you give more context on this issue?

**Comment by qdii** [comment]
I opened this 9 months ago, so I'm afraid the knowledge is gone :/

**Comment by quartztester** [comment]
@qdii You could still try to recreate the issues unless things have suddenly started to work again from re-installing
