### ISSUE TITLE
Followed the standard docker install and not getting the first time setup

### ISSUE THREAD

**Issue by silmarine** [LibrePhotos/librephotos-docker#112]
I followed the standard install exactly, only changing the parts that need to be changed such as the secrets and volume mappings. When I access the webpage I get just a login page. The only thing I did "differently" was that I set it up using portainer and in portainer I loaded the .env file into the stack instead of having the .env file with the compose file. So maybe that's why but all the variables I can check without logging in seem to have worked (I can see the port number is exposed and the correct volume directory has been filled with files).

**Comment by choval** [comment]
Run `docker compose logs backend` and attach the output, I can help you debug it.

**Comment by silmarine** [comment]
Sorry for the late reply, busy holiday season. Your suggested helped me discover the issue myself. The log said that the csrfTrustedOrigins needed http:// or https:// before it, I just had the URL. After adding that, deleting all the created files and volumes, and redeploying it worked as expected. Thanks for the clue!

**Comment by ManiacDC** [comment]
Thanks, I didn't see this in the logs... I was getting weird database errors that were throwing me off; but this was ultimately the cause for me too.
