### ISSUE TITLE
over-engineered

### ISSUE THREAD

**Issue by stevenalanstark** [LibrePhotos/librephotos-docker#126]
is there a simple implementation? First thing I did was throw out the make file, .env, .raw, the proxy ( I needed the proxy after all because there is logic in the proxy ) and made myself a simplified compose.yml. It turns out that things like the container name are hard coded in the proxy? why?? this is far too brittle. docker compose implementation should be simple and straightforward, transportable and configurable.

can you please release a simple implementation?

**Comment by stevenalanstark** [comment]
I'm just going to close this, if there's a minimal compose let me know

**Comment by derneuere** [comment]
Open source projects rely heavily on community contributions and constructive collaboration. If you have suggestions for improving the project, we'd greatly appreciate it if you could either detail them constructively or, even better, open a pull request with your proposed changes. 

Alternatively, you can ask me for a support contract or somebody else do it, if you lack the skill. You can't just expect somebody else to implement your wishes.
