### ISSUE TITLE
New install - cannot change admin options

### ISSUE THREAD

**Issue by warrenhead** [LibrePhotos/librephotos-docker#127]
I'm a new user, using the docker installation. Using version/tag: 2024w28.
With the account I created on first startup, I cannot change any setting on the admin area page.
The two radio buttons for 'allow upload' and 'allow user registration' are not selectable and/or responding.
Looking at the dev console of the browser, I see http 500 in the response, but I don't know how to get more information; the docker logs for the frontend container are empty.

Error shown:

> 14:39:49.227 ZodError: [
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "null",
    "path": [
      "heavyweight_process"
    ],
    "message": "Expected number, received null"
  }
]
    ku http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    get error http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    parse http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    transformResponse http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:725
    u http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    v http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    J0e http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    v6e http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    dispatch http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    b http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    v6e http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    m http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:708
    b6 http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:85
    Qx http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:85
    Afe http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:85
    ry http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:83
    Vft http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:85
    s0 http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:85
    zRe http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:85
    O http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:70
    W http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:70
    EventHandlerNonNull* http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:70
    <anonymous> http://pve-librephotos:3000/assets/index-Bm5HGrBi.js:70
index-Bm5HGrBi.js:708:51486

Looking in the database, my account is super user, so I think this could be a bug.
I also tried this option in my .env file (with a restart of all containers), but it did not help:
userUpload=true

Please advice.

**Comment by quartztester** [comment]
@warrenhead Could you provide more information? Such as OS or otherwise. Also, can you try a reinstall of the entire container instead of restarting it?

**Comment by derneuere** [comment]
This was fixed and will be part of the next release :)
