### ISSUE TITLE
HEAVYWEIGHT_PROCESS

### ISSUE THREAD

**Issue by darrepac** [LibrePhotos/librephotos-docker#13]
Hi

There is a new HEAVYWEIGHT_PROCESS in the env file:
```
# Number of workers, when scanning pictures. This setting can dramatically affect the ram usage.
# Each worker needs 800MB of RAM. Change at your own will. Default is 1.
HEAVYWEIGHT_PROCESS=1
```
Yet:
1/ I do not see any reference to this variable in the default yml file, normal?
2/ can you elaborate more on the difference with the number of gunniworkers ?

thx

**Comment by trowj** [comment]
It's eventually used in directory_watcher.py::scan_photos: https://github.com/LibrePhotos/librephotos/blob/dev/api/directory_watcher.py#L202

It is supposed to spread out the scanning load to speed it up, and it does spawn multiple processes when it kicks off, but there's also a current issue raised (https://github.com/LibrePhotos/librephotos/issues/249) that seems to say only one of them is really...doing anything at any given time.

**Comment by darrepac** [comment]
ok but if the yml file does not have any reference of it, how it can be used?

**Comment by derneuere** [comment]
It was apparently only ever tested with a local installation. I added the variable to the .yml file. It should now work.

**Comment by derneuere** [comment]
It is resolved.
