### ISSUE TITLE
dependency cycle detected: db -> db

### ISSUE THREAD

**Issue by offle** [LibrePhotos/librephotos-docker#132]
Hi,
because of db depends_on: db my docker compose is saying >>>dependency cycle detected: db -> db<<< 
Is this an issue or something with my docker setup?

**Comment by derneuere** [comment]
@sickelap Could you look into this issue? :D

**Comment by zhangyiming748** [comment]
I also encountered the same problem. After running the command`docker compose pull`, the error message is as follows dependency cycle detected: db -> db

**Comment by ChronosCrake** [comment]
Can confirm I also recieve this error when attempting a docker installation. I went ahead and removed the self reference for db in the docker compose file, but then that instead just resulted in a failed healthcheck for the backend container.

**Comment by derneuere** [comment]
This was introduced by recent changes, and I just reverted them. Please pull this repo again and try again :)
