### ISSUE TITLE
Thumbnails access issue with openmediavault

### ISSUE THREAD

**Issue by 2andgi** [LibrePhotos/librephotos-docker#22]
Thumbnails successfully created in protected_media but non accessible via frontend (browser)
![Screenshot 2021-09-02 222805](https://user-images.githubusercontent.com/89306827/131905771-a5749749-1eb3-4898-a8db-9733982d45b9.jpg)
![Screenshot 2021-09-02 222949](https://user-images.githubusercontent.com/89306827/131905774-d1fc5e65-f1ae-4401-b59f-a9f16f1c2370.jpg)
![Screenshot 2021-09-02 223853](https://user-images.githubusercontent.com/89306827/131905776-04ff4813-3cba-4915-bef5-bd1a352c80f8.jpg)

**Comment by 2andgi** [comment]
[ownphotos.log](https://github.com/LibrePhotos/librephotos-docker/files/7101350/ownphotos.log)
[gunicorn_django.log](https://github.com/LibrePhotos/librephotos-docker/files/7101351/gunicorn_django.log)
[rqworker.log](https://github.com/LibrePhotos/librephotos-docker/files/7101353/rqworker.log)
![Screenshot 2021-09-02 224414](https://user-images.githubusercontent.com/89306827/131906485-cffa7f7f-4cba-47cf-aabb-918658cafd3e.jpg)

**Comment by derneuere** [comment]
@2andgi I think this will be probably a nginx issue. Could you send me the logs from your proxy container?

**Comment by 2andgi** [comment]
![Screenshot 2021-09-03 213613](https://user-images.githubusercontent.com/89306827/132051896-db5af2af-a9a3-4b5f-aabf-1ebf5bb81e62.jpg)
[_librephotos_proxy_1_logs.txt](https://github.com/LibrePhotos/librephotos-docker/files/7107924/_librephotos_proxy_1_logs.txt)

**Comment by 2andgi** [comment]
![Screenshot 2021-09-03 214122](https://user-images.githubusercontent.com/89306827/132052376-49a22954-f1ed-4bcb-9b44-a48feeb00b37.jpg)

**Comment by 2andgi** [comment]
[_librephotos_backend_1_logs.txt](https://github.com/LibrePhotos/librephotos-docker/files/7111312/_librephotos_backend_1_logs.txt)

**Comment by derneuere** [comment]
I can't reproduce the error. It seems like it has something to do with WSL, but I am not sure.

**Comment by 2andgi** [comment]
Openmediavault server, other containers works well
All folders (cache, logs, pictures, data, media) was autocreated by docker at compose time
also was trying variant where these folder created by root.

**Comment by 2andgi** [comment]
![2021-09-06](https://user-images.githubusercontent.com/89306827/132239191-5ef4fce0-b7a8-49b5-bb88-49b1546b2aa9.png)
in OMV at ACL permissions for Others: Read/Execute needs to be changed to Read/Write/Execute to files and subfolders

Now it's OK with access
