### ISSUE TITLE
Hierarchy level access issue

### ISSUE THREAD

**Issue by 2andgi** [LibrePhotos/librephotos-docker#23]
![Знімок екрана 2021-09-08 153609](https://user-images.githubusercontent.com/89306827/132511903-0248c372-8160-4902-9cab-6ea2838d52ab.jpg)
Folders and SubFolder in real

![Знімок екрана 2021-09-08 153536](https://user-images.githubusercontent.com/89306827/132511975-1dd688e2-482e-44c9-92c7-5ea7d2342c01.jpg)
How LibrePhoto can access, folder1 only

**Comment by derneuere** [comment]
This issue is tracked here: https://github.com/LibrePhotos/librephotos/issues/136

It will still scan all the subfolders, but they are not shown yet, because of an inefficient implementation. I will close this ticket as it is a duplicate.
