### ISSUE TITLE
Not possible to pass a Redis password as an EVAR

### ISSUE THREAD

**Issue by GoingOffRoading** [LibrePhotos/librephotos-docker#25]
If the user wishes to re-use an existing instance of Redis that has password authentication, that user is unable to do so because an option for a Redis password is not in the:

- Docker Compose: https://github.com/LibrePhotos/librephotos-docker/blob/main/docker-compose.yml
- Evar File: https://github.com/LibrePhotos/librephotos-docker/blob/main/librephotos.env
- Nor 

does it work passing the value manually (Kubernetes example): 

```
env:
            - name: REDIS_PASSWORD
              value: "$password"
```

End user should be able to leverage basic password authentication for Redis, which would bring the authentication configuration for Librephoto to parity with the authentication  on the backend.

**Comment by stavros-k** [comment]
Any news on this? That would be great to have

**Comment by stavros-k** [comment]
> If the user wishes to re-use an existing instance of Redis that has password authentication, that user is unable to do so because an option for a Redis password is not in the:
> 
> * Docker Compose: https://github.com/LibrePhotos/librephotos-docker/blob/main/docker-compose.yml
> * Evar File: https://github.com/LibrePhotos/librephotos-docker/blob/main/librephotos.env
> * Nor
> 
> does it work passing the value manually (Kubernetes example):
> 
> ```
> env:
>             - name: REDIS_PASSWORD
>               value: "$password"
> ```
> 
> End user should be able to leverage basic password authentication for Redis, which would bring the authentication configuration for Librephoto to parity with the authentication on the backend.

Looking through the codebase found this:
https://github.com/LibrePhotos/librephotos/blob/e2a748b859e80cefc933f4191d60e280b406c483/ownphotos/settings.py#L173-L177

So by using `REDIS_PASS` you should be able to set redis password ;)

**Comment by derneuere** [comment]
It's now documented: https://docs.librephotos.com/1/environment_variables/#redis-password
