### ISSUE TITLE
Add latest tag on weekly releases

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos-docker#36]
Now that we have weekly releases which tend to be more stable, we could use the tag latest for these releases. This would reduce errors that occur in the rolling dev tag.

**Comment by quartztester** [comment]
Issue implemented in ['librephotos.env'](https://github.com/LibrePhotos/librephotos-docker/commit/a042eb22dc15f1f50698e1128c74bf1541abad5b). 

Request to close issue.

**Comment by derneuere** [comment]
Thanks for reminding me!
