### ISSUE TITLE
Access to original photos without authorization?

### ISSUE THREAD

**Issue by TripleEmcoder** [LibrePhotos/librephotos-docker#39]
Maybe I am reading it wrong, but it seems that the proxy container openly shares original photos through the /data location:

```
location /data  {
        internal;
        alias /data/;      
    }
```

```
volumes:
      - ${myPhotos}:/data
```

Am I missing something or is the LibrePhotos login/password useless in protecting photos from external access?

**Comment by DalinSeivewright** [comment]
@TripleEmcoder You'll notice the use of the `internal` directive which makes this location only accessible for requests internal to nginx
Here is a link to the docs:  https://nginx.org/en/docs/http/ngx_http_core_module.html#internal

**Comment by varet80** [comment]
> @TripleEmcoder You'll notice the use of the `internal` directive which makes this location only accessible for requests internal to nginx Here is a link to the docs: https://nginx.org/en/docs/http/ngx_http_core_module.html#internal

but what is the purpose of Nginx having access to it?

**Comment by derneuere** [comment]
I think this issue can be closed. I double-checked it. You need an auth header to see any picture.

I think the purpose is just to not get any CORS errors in the browser.
