### ISSUE TITLE
Backend starts before postgres is ready

### ISSUE THREAD

**Issue by rarosalion** [LibrePhotos/librephotos-docker#40]
With the provided docker-compose.yml, the backend starts before postgress is ready (depends_on only waits for the container to be started), and the database initialisation scripts fail, leaving the database empty on the first run.

From [docker.com](https://docs.docker.com/compose/startup-order/): "Compose does not wait until a container is “ready” (whatever that means for your particular application) - only until it’s running."

Starting the services manually using:
- docker compose up -d redis db
- docker compose up -d backend frontend proxy
seems to work (providing you wait for the db to be ready before starting the backend)

I'm not familiar enough with Django to work out how to put a "wait for db to be ready" line in the entrypoint.sh script, but I'm happy to test, or try and help if I can.

Edit: Just figured out a way to do it, and submitted a PR.

**Comment by varet80** [comment]
I do not believe is a wise way to do so! and without a Switch! as this can cause other tools to have issues! like K8s installations!

**Comment by varet80** [comment]
additionally, what about this:
https://stackoverflow.com/questions/35069027/docker-wait-for-postgresql-to-be-running

**Comment by quartztester** [comment]
This way has solved the 404/500/502/ect. error I was getting for backend login request.

OS: Windows 10

I was initially getting multiple sing-in errors when using the regular 'docker-compose up -d'.
[Console-Output.txt](https://github.com/LibrePhotos/librephotos-docker/files/9056442/Console-Output.txt)

Browser Console Errors:

![Screenshot 2022-07-06 115951](https://user-images.githubusercontent.com/91350035/177595877-78ca65db-568e-474c-abf2-ef6ee3525649.png)
[Icon-Manifest-Error.log](https://github.com/LibrePhotos/librephotos-docker/files/9056430/Icon-Manifest-Error.log)
[500-error-1.log](https://github.com/LibrePhotos/librephotos-docker/files/9056432/500-error-1.log)
[Request failed with status code 500.log](https://github.com/LibrePhotos/librephotos-docker/files/9056433/Request.failed.with.status.code.500.log)
[404-error.log](https://github.com/LibrePhotos/librephotos-docker/files/9056435/404-error.log)
[500-error-2.log](https://github.com/LibrePhotos/librephotos-docker/files/9056436/500-error-2.log)
[502-error.log](https://github.com/LibrePhotos/librephotos-docker/files/9056437/502-error.log)

Backend Docker-Desktop logs:
[Docker-Desktop-backend-Logs-1.txt](https://github.com/LibrePhotos/librephotos-docker/files/9056444/Docker-Desktop-backend-Logs-1.txt)
[Docker-Desktop-backend-logs-2.txt](https://github.com/LibrePhotos/librephotos-docker/files/9056445/Docker-Desktop-backend-logs-2.txt)
