### ISSUE TITLE
Installation Crash

### ISSUE THREAD

**Issue by grainsoflight** [LibrePhotos/librephotos-docker#52]
Installer causes docker-compose to crash

**Comment by derneuere** [comment]
I am not sure what you mean by installer. As this issue stands it's hard to pin point the issue. Did you follow this here https://docs.librephotos.com/1/standard_install/ and where did you get stuck?

**Comment by grainsoflight** [comment]
I can attempt it again when Im back at the PC, but I don't recall an error
getting spit out, just that Ubuntu gives me a "docker-compose crashed"
window upon running "docker-compose up -d"
