### ISSUE TITLE
Editing SECRET_KEY breaks login and scanning

### ISSUE THREAD

**Issue by jakekapellen** [LibrePhotos/librephotos-docker#55]
I'm using the docker-compose install. In the .env file, I added the shhhhKey variable after using LibrePhotos for a while to initialize the SECRET_KEY environment variable when the backend gets created. I had the whole thing working before this, but adding that variable broke things; I can no longer login.

I also tried scanning using "python3 manage.py scan" which gives a BadSignature exception. Running scan from CLI without SECRET_KEY initialized gives  an ImproperlyConfigured exception saying that SECRET_KEY must not be empty.

I'm assuming this variable is used to encrypt the database or something, as it works fine on a clean install. You should update install instructions and/or the docket image to make this more clear, since you cannot fix this afterwards.

**Comment by derneuere** [comment]
The secret.key is an actual file, which should be in your log folder. It gets used as a default key when shhhhKey is not supplied. So the backend should always have a secret key. Did you clean the log folder or how did the secret.key get missing? :sweat_smile:

**Comment by jakekapellen** [comment]
I didn't clean it or anything. I figured it was some kind of issue with the image or something, but I'm not sure.

If this is likely a corrupted thing on my end, we can close the issue.
