### ISSUE TITLE
Invalid compose file due to depends_on

### ISSUE THREAD

**Issue by Wahala** [LibrePhotos/librephotos-docker#65]
Hi, on a new instalation (first time user) I'm getting this error when executing `docker-compose up -d`:

> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.backend.depends_on contains an invalid type, it should be an array

If I change the version in the docker-compose.yml file from 3.8 to 2.2 then it does run ok.
Similar issue is described here:
https://stackoverflow.com/questions/71060072/docker-compose-depends-on-with-condition-invalid-type-should-be-an-array

**Comment by derneuere** [comment]
I will not maintain older versions of docker-compose. Upgrade it or maintain your docker-compose file yourself.
