### ISSUE TITLE
LibrePhotos Docker Startup Errors

### ISSUE THREAD

**Issue by Vanguard4893** [LibrePhotos/librephotos-docker#66]
Hi there,

I'm trying to get LIbrePhotos running on some of my infrastructure, however I'm having some problems. When docker-compose up -d is called, the system never properly starts, and the backend container logs show many errors, examples below:

The frontend does start, but obviously isn't usable since the backend workers never get off the ground.

rqworker.log:

> OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/matplotlib/font_manager.py", line 1429, in <module>
>     fontManager = json_load(_fmcache)
>   File "/usr/local/lib/python3.10/dist-packages/matplotlib/font_manager.py", line 1012, in json_load
>     with open(filename, 'r') as fh:
> FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/matplotlib/fontlist-v330.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/code/manage.py", line 11, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 377, in execute
>     django.setup()
>   File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/usr/local/lib/python3.10/dist-packages/django/apps/registry.py", line 114, in populate
>     app_config.import_models()
>   File "/usr/local/lib/python3.10/dist-packages/django/apps/config.py", line 211, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/code/api/models/__init__.py", line 1, in <module>
>     from api.models.album_auto import AlbumAuto
>   File "/code/api/models/album_auto.py", line 6, in <module>
>     from api.models.person import Person
>   File "/code/api/models/person.py", line 7, in <module>
>     from api.models.photo import Photo
>   File "/code/api/models/photo.py", line 21, in <module>
>     from api.im2txt.sample import im2txt
>   File "/code/api/im2txt/sample.py", line 27, in <module>
>     vocab = pickle.load(f)
>   File "/code/api/im2txt/build_vocab.py", line 5, in <module>
>     from pycocotools.coco import COCO
>   File "/usr/local/lib/python3.10/dist-packages/pycocotools/coco.py", line 49, in <module>
>     import matplotlib.pyplot as plt
>   File "/usr/local/lib/python3.10/dist-packages/matplotlib/pyplot.py", line 36, in <module>
>     import matplotlib.colorbar
>   File "/usr/local/lib/python3.10/dist-packages/matplotlib/colorbar.py", line 44, in <module>
>     import matplotlib.contour as contour
>   File "/usr/local/lib/python3.10/dist-packages/matplotlib/contour.py", line 16, in <module>
>     import matplotlib.font_manager as font_manager
>   File "/usr/local/lib/python3.10/dist-packages/matplotlib/font_manager.py", line 1431, in <module>
>     _rebuild()
>   File "/usr/local/lib/python3.10/dist-packages/matplotlib/font_manager.py", line 1424, in _rebuild
>     fontManager = FontManager()
>   File "/usr/local/lib/python3.10/dist-packages/matplotlib/font_manager.py", line 1069, in __init__
>     timer.start()
>   File "/usr/lib/python3.10/threading.py", line 928, in start
>     _start_new_thread(self._bootstrap, ())
> RuntimeError: can't start new thread

gunicorn_image_stability.log:

> OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 8: Operation not permitted
> OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
> Traceback (most recent call last):
>   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
>   File "/usr/local/lib/python3.10/dist-packages/gevent/baseserver.py", line 398, in serve_forever
>     self.start()
>   File "/usr/local/lib/python3.10/dist-packages/gevent/baseserver.py", line 336, in start
>     self.init_socket()
>   File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 1546, in init_socket
>     self.update_environ()
>   File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 1558, in update_environ
>     name = socket.getfqdn(address[0])
>   File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 304, in getfqdn
>     hostname, aliases, _ = gethostbyaddr(name)
>   File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 276, in gethostbyaddr
>     return get_hub().resolver.gethostbyaddr(ip_address)
>   File "/usr/local/lib/python3.10/dist-packages/gevent/resolver/thread.py", line 66, in gethostbyaddr
>     return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/gevent/pool.py", line 161, in apply
>     return self.spawn(func, *args, **kwds).get()
>   File "/usr/local/lib/python3.10/dist-packages/gevent/threadpool.py", line 526, in spawn
>     self.adjust()
>   File "/usr/local/lib/python3.10/dist-packages/gevent/threadpool.py", line 472, in adjust
>     self._adjust_step()
>   File "/usr/local/lib/python3.10/dist-packages/gevent/threadpool.py", line 452, in _adjust_step
>     self._add_thread()
>   File "/usr/local/lib/python3.10/dist-packages/gevent/threadpool.py", line 479, in _add_thread
>     self._WorkerGreenlet(self)
>   File "/usr/local/lib/python3.10/dist-packages/gevent/threadpool.py", line 100, in __init__
>     start_new_thread(self._begin, ())
> RuntimeError: can't start new thread
> 2022-08-20T08:24:07Z <Greenlet at 0x7f43a27ba0e0: <bound method BaseServer.serve_forever of <WSGIServer at 0x7f439f306770 fileno=6 address=0.0.0.0:8002>>> failed with RuntimeError

This is a fresh Debian 10 system, I did check process limits, and there are none for the root user. The same .env config runs fine on two other machines, so I'm at a bit of a loss!

Cheers

**Comment by derneuere** [comment]
Hmm, I never encountered this issue. What value did you use for the gunniWorkers? What happens if you reduce them to 1?

**Comment by Vanguard4893** [comment]
gunniWorkers was set to the default of 2, changing it to 1 and reloading has no effect.

Cheers

**Comment by Vanguard4893** [comment]
Hi there,

I've cracked the problem! Seems LibrePhotos is a bit sensitive to Docker versions, forcing an update from V18.x to V20.x fixed the issue.

Cheers
