### ISSUE TITLE
Allow custom container names for frontend and backend

### ISSUE THREAD

**Issue by meienberger** [LibrePhotos/librephotos-docker#72]
Hello, I'm currently working on adding LibrePhotos as an application to [Runtipi](https://github.com/meienberger/runtipi) as users have requested. However I'm unable to change the docker container names inside the compose file. This is due to reallibrephotos/librephotos-proxy only using `frontend` and `backend` as host names in nginx.

I cannot use those names as they are too common and would potentially collide with other services running.

**Comment by derneuere** [comment]
You can use the make command to change the docker-compose.yml :)

https://github.com/LibrePhotos/librephotos-docker#to-use-your-own-container-names

**Comment by meienberger** [comment]
Ah my bad... I forgot to map the custom nginx.conf to the container
