### ISSUE TITLE
Ability to pass in backend and frontend names to containers

### ISSUE THREAD

**Issue by erahhal** [LibrePhotos/librephotos-docker#73]
I'm running on a system with many containers, and using `backend` and `frontend` for container names creates the potential for a name collision.  Allow for using arbitrary container names, passing in the names to the containers using environment variables.  Or at least using `librephotos-backend` and `librephotos-frontend` instead.

**Comment by derneuere** [comment]
You can use the make command to change the docker-compose.yml :)

https://github.com/LibrePhotos/librephotos-docker#to-use-your-own-container-names

**Comment by erahhal** [comment]
How does that work with registry images?  I'm running in a constrained environment with a pre-built config that pulls from the public registry.

**Comment by erahhal** [comment]
Also, is there a reason NOT to make this change?  It seems like avoiding namespace conflicts by default is a good thing.
