### ISSUE TITLE
Docker error (frontend)

### ISSUE THREAD

**Issue by Benni620** [LibrePhotos/librephotos-docker#79]
I used the official instruction for setting up the containers with Docker Compose. But I get this error:

`docker-compose up -d
WARNING: The HEAVYWEIGHT_PROCESS variable is not set. Defaulting to a blank string.
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating network "librephotos-docker_default" with the default driver
Creating redis    ... done
Creating frontend ... error
Creating db       ... done

ERROR: for frontend  Cannot start service frontend: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/serve": stat /serve: permission denied: unknown
Creating backend  ... done

ERROR: for frontend  Cannot start service frontend: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/serve": stat /serve: permis                                        sion denied: unknown
ERROR: Encountered errors while bringing up the project.
`

Is there a solution for fixing this?

I use Docker version **20.10.21**, build baeda1f on **Debian** GNU/Linux **10 (buster)**

Greetings benni620

**Comment by ajcarrascod** [comment]
Try set the variable as it show  here:
[https://github.com/LibrePhotos/librephotos/issues/25#issuecomment-816487925](url)

It worked to me

**Comment by Benni620** [comment]
You mean the "WARNING: The HEAVYWEIGHT_PROCESS variable is not set." ? I think that is not the problem why the container didn´t start.
The error is my problem.

**Comment by Nerodacles** [comment]
@DigitalWarrior With #81 this is not gonna happen.

**Comment by DigitalWarrior** [comment]
Closed #81 resolved this issues. Thank you @Nerodacles

**Comment by Benni620** [comment]
Yes, this solves the problem of the warning being displayed.

But unfortunately it's still the case that I get the error and can't get the frontend container started. Doesn't seem to be a general problem, but does anyone have any ideas?

Thanks and greetings
