### ISSUE TITLE
Docker Frontend permission error

### ISSUE THREAD

**Issue by Benni620** [LibrePhotos/librephotos-docker#83]
I have a problem with the docker container. When I follow the instructions I get an error when starting the frontend:

`ERROR: for frontend Cannot start service frontend: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/serve": stat /serve: permission denied: unknown
`
Can anyone help me with this?

I use Docker version 20.10.22, on Debian 10 (buster)

I found out that the Dockerfile contains the following information: ENTRYPOINT ["/serve"]
This is what will cause the error? Can I change the permissions? I do not know where /serve can be found.

**Comment by derneuere** [comment]
This is most likely an issue with Debian 10 and your specific docker version. The frontend is a simple container, which contains the HTML, JavaScript and CSS and runs a static file server, which starts with the serve command.
