### ISSUE TITLE
No apparent way to reset/delete password

### ISSUE THREAD

**Issue by smontanaro** [LibrePhotos/librephotos-docker#85]
I followed the instructions to download and spin up the docker image:

https://docs.librephotos.com/1/standard_install/

I created an account, using my password manager to generate a password. Expecting it to save the login/password pair, I didn't copy the password. Now it wants me to login, but of course I can't, because the credentials aren't in my password manager. The user interface doesn't seem to provide a "recover/reset password" or "create account" link besides the original one.

I stopped the docker image, removed it from the dashboard then ran ``docker-compose up -d`` again. I expected to start over, but I'm just getting the standard login prompt again. I got more intrusive, stopping and deleting the librephotos-docker container as well as all images. Lather, rinse, repeat, and I'm back to the same login prompt with no way to create a new login or reset my password.

I've clearly failed to delete some crucial file somewhere. I would have thought all the state required for this would be inside the images. Can someone help me get restarted?

**Comment by sickelap** [comment]
After terminating all containers, remove `${data}/db` folder. Then restart the project.
Or another option is to just reset the password. That you can do this by running the following command:
```
docker run -it backend python manage.py changepassword <username> 
```

**Comment by smontanaro** [comment]
Thanks. Removing ${data}/db seemed simplest. That worked great.
