### ISSUE TITLE
Failed to install on a Raspberry 4 with 64bits architecture

### ISSUE THREAD

**Issue by taophp** [LibrePhotos/librephotos-docker#90]
I tried to install LibrePhotos-docker on my Raspberry Pi 4 64bits. Here what happened:
```
$ docker compose up -d
[+] Running 0/5
 ⠼ redis Pulling                                                                                                                                                                                           1.5s
 ⠼ db Pulling                                                                                                                                                                                              1.5s
 ⠼ proxy Pulling                                                                                                                                                                                           1.5s
 ⠿ frontend Error                                                                                                                                                                                          1.5s
 ⠿ backend Error                                                                                                                                                                                           1.5s
no matching manifest for linux/arm/v7 in the manifest list entries
```
I saw on Github that the arm64 architecture is available, so I suppose it should be only a tagging problem.

**Comment by ippocratis** [comment]
> I tried to install LibrePhotos-docker on my Raspberry Pi 4 64bits. Here what happened:

Raspbian forces 32bit
Are you sure you run a 64bit os?

`uname -m` says aarch64?

**Comment by taophp** [comment]
@ippocratis That's not true any more: you can set up Raspbian to be 64bit, adding this line to `/boot/config`:
```
arm_64bit=1
```
And so you get:
```
$ uname -m
aarch64
```
Also, you can simply use the last Raspberry Pi OS, which is 64bits.

**Comment by ippocratis** [comment]
I don't know then

Docker pull supports tags and digest
maybe pull latest arm this way and use that image in docker compose?

`docker pull [OPTIONS] NAME[:TAG|@DIGEST]`

Latest arm diggest

`docker pull reallibrephotos/librephotos:latest@sha256:16fe32dfdbbe2387232156e7ff1b019bbd7a0d7636b7d0135730b2c5c6463df5`
