### ISSUE TITLE
Search display blank Page

### ISSUE THREAD

**Issue by webidisk** [LibrePhotos/librephotos-docker#95]
Hello; 
Sorry but can't find version number on the  web UI to report installed version.
I think I found small issues:
To reproduce:
1. goto main page and click on Photos
2.  on the search enter anything (don't click on any of the results) and press enter 
This will show a black page (no menu)  and you need to click refresh to get back to the Photos page

First time user I just started using LibrePhotos
Thank you for your support and great product...

**Comment by derneuere** [comment]
Please report this issue in the [main repository](https://github.com/LibrePhotos/librephotos/issues) and also post your browser logs :)
